---
title: "Untitled"
author: "Martyna Muszczek"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Libraries

```{r}
library("tidyverse")

```

### Plot theme

```{r}
theme(theme_bw()+theme(legend.position = "top"))
```

### Load quantified data

```{r}
msqrob <- read.delim("data/msqrob_culture_vs_xeno.tsv")

#FC values
msqrob_diff <- msqrob[,19:26]
#Intensity values
msqrob <- msqrob[1:20]
```

### Tidying up: drop NAs, truncate Gene names

```{r}
#drop nas
msqrob <- drop_na(msqrob)

# Tidy up gene groups - getting rid of mouse part and setting as rownames
msqrob$Gene <- str_replace(msqrob$Gene, pattern = "_HUMAN;.+|_HUMAN", replacement = "")
msqrob <- column_to_rownames(msqrob, "Gene")
```

### Correlation matrix: technical replicates and after msqrob

```{r}
library(corrplot)
# AFTER MAXLFQ BEFORE MSQROB
corr <- cor(log2(maxlfq), use="complete.obs")
corrplot(corr, method = "color", hclust.method = "ward.D2", is.corr = FALSE, col = COL1("OrRd"))

# AFTER MSQROB
corr <- cor(msqrob[1:18])
corrplot(corr, method = "color", hclust.method = "ward.D2", is.corr = FALSE, col = COL1("OrRd"))
```

### Normalisation: MA plot, quantile normalisation

```{r}
mat <- as.matrix(msqrob[1:18])


qnorm <- limma::normalizeQuantiles(mat)
```

### Global heatmap

```{r}
# Global heatmap-----------------------------------------------------------------------
annot_col <- data.frame(
  Condition.L1 = as.factor(
    c(rep(c("2D", "3D.young", "3D.old"), each = 4),
      rep(c("PDX.2D", "PDX.3D"), each = 3))),
  Condition.L2 = as.factor(
    c(rep("2D", 4), 
      rep("3D", 8), 
      rep("PDX", 6))))

row.names(annot_col) <- colnames(msqrob)[1:18]

library(RColorBrewer)
annot_colors <- list(Condition.L1 = rev(brewer.pal(5, "Paired")),
                     Condition.L2 = c("firebrick1", "darkgreen", "blue"))

names(annot_colors$Condition.L1) <- levels(annot_col$Condition.L1)
names(annot_colors$Condition.L2) <- levels(annot_col$Condition.L2)

pheatmap::pheatmap(msqrob[1:18],
           scale = "row",
           show_rownames = FALSE,
           clustering_distance_cols = "euclidean",
           clustering_distance_rows = "correlation",
           annotation_col = annot_col,
           annotation_colors = annot_colors,
           main = "Global heatmap")
```

### PCA 

```{r}
# PCA----------------------------------------------------------------------------
library(PCAtools)

#pca
p <- pca(mat, metadata = annot_col, scale = TRUE)

png("figures/pca.png")
biplot(p, 
       lab = colnames(mat), 
       labSize = 5, 
       showLoadings = FALSE,
       boxedLoadingsNames = FALSE, 
       colby = "Condition.L1",
       colkey = annot_colors$Condition.L1,
       title = "Pre-normalisation",
       encircle = TRUE,
       hline = 0, 
       vline = 0)
dev.off()

screeplot(p)
```
