---
title: "GSEA-enriched Molecular Function GOsim terms"
subtitle: "- overlap in at least 2/3 cell lines"
author: "Martyna Muszczek"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: yeti
    toc: true
    toc_float: 
      collapsed: false
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width = 11, warning=FALSE, message=FALSE, echo=FALSE)
knitr::opts_knit$set(verbose = FALSE, progress = FALSE)
options(knitr.duplicate.label = "allow")
load("C:/Users/Windows/Documents/R_projects/RR_proteomics/.RData")
library(tidyverse)
library(pheatmap)
library(knitr)
```

```{css, echo=FALSE}
h1 {
font-size: 25px;
}
```

```{r plots, results="asis"}

FC.matrix = FC
mean.matrix = gr.means
term.descr = term.desc.mf

terms <- term.descr$ID

# order colnames group-wise
order <- colnames(mean.matrix) %>% str_replace_all(pattern = "MIAPACA|PANC|CFPAC", replacement = "") %>% unique()
order[1] <- str_c(order[1],"$")

temp <- c()
for (i in order) {
  temp <- c(temp, str_which(colnames(mean.matrix), pattern = i))
}
mean.matrix.gr <- relocate(mean.matrix, all_of(temp))

for (i in terms) {
  curr.term.desc <- term.descr %>% filter(ID == i) %>% pull(Description)
  term.genes <- term.descr %>% filter(ID == i) %>% pull(Genes) %>% unlist()
  # determine figure height
  if(length(term.genes) < 20){
    height <- 5
  } else if(length(term.genes) > 20 && length(term.genes) <= 40) {
    height <- 6
  } else if(length(term.genes) > 40 && length(term.genes) <= 60) {
    height <- 7
  } else if(length(term.genes) > 60 && length(term.genes) <= 90) {
    height <- 8
  }
  
  # Means grouped cell.line-wise
  if (length(term.genes) > 20) {
    .pl1 <- mean.matrix %>% filter(rownames(mean.matrix) %in% term.genes) |>
      pheatmap::pheatmap(cluster_cols = FALSE,
                         cluster_rows = TRUE,
                         silent = TRUE,
                         angle_col = 45,
                         fontsize_row = 7,
                         border_color = "black",
                         gaps_col = c(5,10,15),
                         col=colorRampPalette(c("cornflowerblue","white","red"))(100))
  } else if (length(term.genes) <= 20) {
    .pl1 <- mean.matrix %>% filter(rownames(mean.matrix) %in% term.genes) |>
      pheatmap::pheatmap(cluster_cols = FALSE,
                         cluster_rows = TRUE,
                         silent = TRUE,
                         angle_col = 45,
                         display_numbers = TRUE,
                         fontsize_number = 10,
                         fontsize_row = 7,
                         number_color = "black",
                         border_color = "black",
                         gaps_col = c(5,10,15),
                         col=colorRampPalette(c("cornflowerblue","white","red"))(100))
  }
  # Means grouped experimental group-wise
  
  if (length(term.genes) > 20) {
    .pl2 <- mean.matrix.gr %>% filter(rownames(mean.matrix.gr) %in% term.genes) |>
      pheatmap::pheatmap(cluster_cols = FALSE,
                         cluster_rows = TRUE,
                         silent = TRUE,
                         angle_col = 45,
                         fontsize_row = 7,
                         border_color = "black",
                         gaps_col = c(3,6,9,12,15),
                         col=colorRampPalette(c("cornflowerblue","white","red"))(100))
  } else if (length(term.genes) <= 20) {
    .pl2 <- mean.matrix.gr %>% filter(rownames(mean.matrix.gr) %in% term.genes) |>
      pheatmap::pheatmap(cluster_cols = FALSE,
                         cluster_rows = TRUE,
                         silent = TRUE,
                         angle_col = 45,
                         display_numbers = TRUE,
                         fontsize_number = 10,
                         fontsize_row = 7,
                         number_color = "black",
                         border_color = "black",
                         gaps_col = c(3,6,9,12,15),
                         col=colorRampPalette(c("cornflowerblue","white","red"))(100))
  }
  # Log2FC matrix
  
  if (length(term.genes) > 20) {
    .pl3 <- FC.matrix %>% filter(rownames(FC.matrix) %in% term.genes) |>
      pheatmap::pheatmap(cluster_cols = FALSE,
                         cluster_rows = TRUE,
                         silent = TRUE,
                         angle_col = 45,
                         fontsize_row = 7,
                         border_color = "black",
                         gaps_col = c(3,6,9,12,15),
                         col=colorRampPalette(c("cornflowerblue","white","red"))(100))
  } else if (length(term.genes) <= 20) {
    .pl3 <- FC.matrix %>% filter(rownames(FC.matrix) %in% term.genes) |>
      pheatmap::pheatmap(cluster_cols = FALSE,
                         cluster_rows = TRUE,
                         silent = TRUE,
                         angle_col = 45,
                         display_numbers = TRUE,
                         fontsize_number = 10,
                         fontsize_row = 7,
                         number_color = "black",
                         border_color = "black",
                         gaps_col = c(3,6,9,12,15),
                         col=colorRampPalette(c("cornflowerblue","white","red"))(100))
  }
  desc <- cat("\n\n##", sprintf("%s (%s)",curr.term.desc, i), "\n\n")
  cap <- paste0(i)
  cat("\n\n")
  
  cat(knitr::knit_child(text = c(
  "## {.tabset}",
  "",
  "### Means cell line-wise",
  "",
  "```{r, fig.height={{height}}}",
  ".pl1",
  "```",
  "",
  "### Means exp.group-wise",
  "",
  "```{r, fig.height={{height}}}",
  ".pl2",
  "```",
  "",
  "### Log2FC",
  "",
  "```{r, fig.height={{height}}}",
  ".pl3",
  "```"
)))
  
}  

 
```


