---
title: "Untitled"
author: "Martyna Muszczek"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: yeti

---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning=FALSE)
knitr::opts_knit$set(root.dir ="C:/Users/Windows/Documents/R_projects/RR_proteomics")
options(knitr.duplicate.label = "allow")
load("C:/Users/Windows/Documents/R_projects/RR_proteomics/.RData")
```

# Header test ------------------------------------------------------------------------
<hr style="border:1px solid gray">
# HEader test2------------------------------------------------------------------------
________________________________________________________________________________

```{r fig.width=12, fig.height=5}
library(ggpubr)
library(tidyverse)
library(ggplot2)

sum_gene_occ %>% 
  filter(Count>40) |> 
  ggbarplot(x = "Gene", y="Count", 
            fill = "steelblue",
            label=TRUE,
            xlab="Gene symbol",
            ylab="Gene count",
            title = "Top gene count in WikiPathways GSEA-enriched terms in all comparisons")+
  font("x.text", size = 9)
```

```{r fig.width=12, fig.height=8}
filtr2 <- sum_gene_occ %>% filter(Count > 40) %>% pull(Gene)

comp_gene_occ %>%
  filter(Gene %in% filtr2) |>
  ggbarplot(x="Gene", y="CompCount",
            fill = "steelblue",
            xlab = "Gene symbol",
            ylab = "Gene count",
            title = "Top gene count in WikiPathways GSEA-enriched terms in each comparison") |>
  facet(facet.by = "Comp", ncol = 1)+
  geom_text(aes(label=CompCount), nudge_y = 6)+
  font("xy.text", size = 8)
```

